### ISSUE TITLE
Don't suggest using Vim

### ISSUE THREAD

**Issue by pabrams** [esdc-devcop/ESDC-Development-Setup#16]
The readme has the following excerpt:

_Suggested Settings:

Use 'Vim' as the default editor_

If we want to encourage people to use this stuff, we should not encourage them to use Vim as their default editor.  The only people who should use Vim are Vim experts.

**Comment by s-laugh** [comment]
When dealing with git, the alternatives to Vim are more complex and more prone to errors, imo. So it is still worth while to learn the basics of Vim when learning Git, which really is quite easy to learn.

**Comment by pabrams** [comment]
Every time I'm in VIM, I find I don't know how to make changes, how to save them, or how to exit the editor.  In my opinion, I shouldn't have to read any instructions on how to do these things - I never had to "learn" anything special to get Notepad++ to do these things.

**Comment by s-laugh** [comment]
It's a bit of a challenging argument, I hear your point, it's one more tool to learn that has a bit of a learning curve to it. At the same time, should we be encouraging the use of tools that are sub-par or less effective? If so, then why recommend Git at all?

**Comment by pabrams** [comment]
Are you arguing that Vim is more effective than, for example, Notepad++?  I suppose it depends on what your goal is, but I think one of the main goals here is to minimize barriers to entry, and so a shallow learning curve is very important. I don't use Vim much (hardly at all), but what's so great about it that offsets the steep learning curve?  The only one I can think of is that if a person learns all the hotkeys, they'll probably be slightly more efficient, in the long run, editing text with Vim than with Notepad++.  Even then, I'm not convinced, because I'd bet it's possible to get Notepad++ to emulate Vim.

**Comment by s-laugh** [comment]
I would be arguing that VIM is not only more effective, but the better practice. 
From experience, almost every higher performing git developer uses VIM or something command line based to avoid context switching, because it slows you down and increases the chance of introducing errors.

The main purpose of this repo existing is for the proxy scripts, suggesting Git is a secondary helping you along the way, suggesting Vim under that is also just nudging someone towards best practices.

VIM tutorial 101, these are the only commands I've ever used:  
`a` = append (to start editing the lines)  
`esc` = exit (return to vim cmd)
`:qw` = quit and write file (save and exit)

**Comment by StdGit** [comment]
I'm using VSStudio, and there is many emulators of vim
https://vi.stackexchange.com/questions/7138/can-i-use-vim-with-visual-studio

**Comment by pabrams** [comment]
Closing - will try Vim

**Comment by pabrams** [comment]
But, then again, look at what the git installer says:

![image](https://user-images.githubusercontent.com/1376688/94166332-2d133780-fe59-11ea-85d4-228e735cc54a.png)

**Comment by s-laugh** [comment]
Understandable, however the suggestion is to use a GUI tool, I wouldn't recommend that because that's context switching which will make you less efficient. At the end of the day, it's still just a recommendation, use whatever works best for you (but dismissing something because it's hard to learn, isn't the best reason).

**Comment by pabrams** [comment]
Some argue that the inefficient context switching comes from using VI, because most of our tools are gui-based, not cli-based.  I don't know many people who use command line options for their email client, etc., but maybe I'm not hanging with the right crowd...

**Comment by pabrams** [comment]
Some argue that the inefficient context switching comes from using VI, because most of our tools are gui-based, not cli-based.  I don't know many people who use command-line-based email clients, etc., but maybe I'm not hanging with the right crowd...
I personally think that, all else being equal, "hard to learn" is an excellent reason not to use a tool.
The argument I've been trying to make is that for most people that we're targeting (people that don't already use git), it will be better for them not to crack open Vi, at least not just yet.  This isn't about what's best for you, it's about what's best for the average person following the readme.

**Comment by s-laugh** [comment]
Valid points. I would never recommend using a GUI for Git but that's a whole other thing... 
Either way we can argue all day long on our personal preferences, however I feel like a healthy discussion here as to whether a change should be made (and to what) should be had - see if there is any kind of consensuses among others.

**Comment by StdGit** [comment]
From a beginner point of view, VsCode is the best, because it allows you to learn git easily.
- You have a menu with the principal git commands
- You could work in a shell (Bash) with your CLI editor (Vi) in the same windows
- You could watch the git command that are generated in the output.
- You have a lot of extensions
- It's Open Source

Other tools:

GitHub Desktop has some glitches when I worked with
GitKraken could be good.

P.S. The best tool is the one you perform the best with.

**Comment by pabrams** [comment]
I agree with the VS Code recommendation, for people using VS Code. And maybe even for Visual Studio users.

**Comment by pabrams** [comment]
>>P.S. The best tool is the one you perform the best with.

Of course, but this is about which tool should be suggested to newcomers by
default. If I was a newcomer to git, and as I was installing, someone
suggested I use Vi as my text editor, I'd probably be like "yeah sure
whatever; fine", if I didn't know what Vi was. Then later, as I'm
struggling to use git, which is known to be not tremendously easy to learn
in the first place, I then need to edit a file ("ah finally , something
that will be easy"), that could easily be the straw that makes git heavier
than what I want right now.

**Comment by StdGit** [comment]
My issue with git was due to multiple accounts interfering together, the fact that I used Github desktop and the rerouting of my computer causing delay. Monitoring or bad network configuration is causing a lot of issues...

Graphic user interface(GUI) like VScode helps a lot if you have a bad memory, if you don't know your commands, or if you have to type many commands to do something.
But if you have a good memory and already know Git, Vi could be a good choice.

Perhaps you could offer 2 tools...

**Comment by pabrams** [comment]
@StdGit Individual developers could still decide which tool to use; this issue is only about which one of those we recommend for people installing git (presumably for the first time).  
The fix for this issue, in my opinion, is either to remove the line from the DevCop readme that suggests using Vim, or to add more text in there, warning that Vim could have a steep learning curve, and therefore some may wish to use a text editor that is more intuitive for them, such as VSCode, or Notepad++, or even Notepad itself.

**Comment by StdGit** [comment]
I agree

**Comment by s-laugh** [comment]
I agree with you @pabrams. However, I would lean towards replacing it with "Recommended using Git defaults on setup".

**Comment by StdGit** [comment]
My last comments
I prefer a GUI editor and I would recommend that.

If you are from unix/linux world, I guess you will prefer vi or vim

So recommend both. (With some explications to help Developers to make a wise decision)

FYI from 

https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration
core.editor

By default, Git uses whatever you’ve set as your default text editor via one of the shell environment variables VISUAL or EDITOR, or else falls back to the vi editor to create and edit your commit and tag messages. To change that default to something else, you can use the core.editor setting:

$ git config --global core.editor emacs

Now, no matter what is set as your default shell editor, Git will fire up Emacs to edit messages.

---

And from http://web.mit.edu/6.005/www/fa14/tutorial/git/config.html

On Windows, if you use Git Bash the default editor will be Vim. Vim is another text editor, like nano or notepad. In order to get started Vim there are only a few commands you must remember.

**Comment by s-laugh** [comment]
Recommendations shouldn't be based on personal preference, but a combination of commonly used, considered best practice and can be supported. But recommendations are just that, recommendations; so people should still feel welcome to use what they prefer. Recommending more than one option, doesn't help an undecided user determine what to do (even if there is explanations).
